# Generated by Django 3.2.8 on 2022-05-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.TextField(unique=True)),
                ('dv', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('merchant_registration', models.TextField()),
                ('img', models.ImageField(default='Profile_Client/foto.jpg', upload_to='Photo_Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.municipality')),
                ('type_documentI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_document_identification')),
                ('type_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_organization')),
                ('type_regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_regime')),
            ],
        ),
    ]
