# Generated by Django 3.2.8 on 2022-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='account_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='bank',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='ref',
            field=models.TextField(default=''),
        ),
    ]
