# Generated by Django 3.2.8 on 2022-05-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_acceptance',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
