# Generated by Django 3.2.8 on 2022-05-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_acceptance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_acceptance',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
