# Generated by Django 3.2.13 on 2022-05-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_subcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
