# Generated by Django 3.2.13 on 2022-05-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleoyee', '0007_alter_empleoyee_hiring_date'),
        ('company', '0008_auto_20220531_1405'),
        ('inventory', '0005_auto_20220530_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('quanty', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('empleoyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleoyee.empleoyee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
