# Generated by Django 3.2.13 on 2022-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_inventory',
            name='price',
            field=models.TextField(default=0),
        ),
    ]
