# Generated by Django 3.2.13 on 2022-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_shopping_inventory_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_inventory',
            name='quanty',
            field=models.TextField(default=''),
        ),
    ]
