# Generated by Django 3.2.13 on 2022-05-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_shopping_inventory_quanty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_inventory',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
