# Generated by Django 3.2.13 on 2022-05-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_shopping_inventory_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_inventory',
            name='number_invoice',
            field=models.TextField(default=0),
        ),
    ]
