# Generated by Django 3.2.13 on 2022-05-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20220531_2208'),
        ('inventory', '0012_shopping_inventory_number_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_inventory',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
