# Generated by Django 3.2.13 on 2022-06-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20220601_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_inventory',
            name='code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
