# Generated by Django 3.2.8 on 2022-05-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll_document',
            name='company',
        ),
        migrations.DeleteModel(
            name='BackUp_Payroll',
        ),
        migrations.DeleteModel(
            name='Payroll_Document',
        ),
    ]
