# Generated by Django 3.2.8 on 2022-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20220520_0859'),
        ('payroll', '0002_auto_20220520_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_document', models.FileField(upload_to='Payroll_Document')),
                ('month', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
