# Generated by Django 3.2.8 on 2022-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_document',
            name='month',
            field=models.CharField(max_length=15),
        ),
    ]
