# Generated by Django 3.2.8 on 2022-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payroll_document_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_document',
            name='anio',
            field=models.IntegerField(default=0),
        ),
    ]
