# Generated by Django 3.2.8 on 2022-06-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20220609_1614'),
        ('payroll', '0005_payroll_document_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutive_Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
