# Generated by Django 3.2.8 on 2022-06-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_consecutive_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_document',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
