# Generated by Django 3.2.8 on 2022-05-06 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentIdentification', models.TextField(unique=True)),
                ('business_name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('certificate_generation_date', models.CharField(max_length=10)),
                ('certificate_expiration_date', models.CharField(max_length=10)),
                ('resolution_generation_date', models.CharField(max_length=10)),
                ('resolution_expiration_date', models.CharField(max_length=10)),
                ('block', models.BooleanField(default=False)),
                ('token', models.TextField()),
                ('user', models.TextField()),
                ('password', models.TextField()),
                ('logo', models.ImageField(default='Logo_Company/default.png', upload_to='Logo_Company')),
                ('cod_bars', models.BooleanField(default=True)),
                ('resolution_number', models.TextField(default='18760000001')),
                ('prefix', models.TextField(default='SETP')),
                ('license', models.BooleanField(default=False)),
                ('date_register', models.TextField(default=datetime.date(2022, 5, 6))),
                ('payment_date', models.TextField(default=datetime.date(2022, 5, 6))),
            ],
        ),
        migrations.CreateModel(
            name='License_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_license', models.BooleanField(default=False)),
                ('registration_date', models.TextField()),
                ('due_date', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Files_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.FileField(blank=True, default='', null=True, upload_to='RUT_Company')),
                ('chamber_of_commerce', models.FileField(blank=True, default='', null=True, upload_to='Chamber_Of_Commerce_Company')),
                ('img_document_identification', models.FileField(blank=True, default='', null=True, upload_to='Img_Document_Identification')),
                ('name_company', models.TextField(default='')),
                ('documentIdentification', models.TextField(default='', unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('finish_date', models.CharField(default='', max_length=10)),
                ('cancellation_date', models.CharField(default='', max_length=10)),
                ('seller', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='files_company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.files_company'),
        ),
        migrations.AddField(
            model_name='company',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.municipality'),
        ),
        migrations.AddField(
            model_name='company',
            name='type_documentI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_document_identification'),
        ),
        migrations.AddField(
            model_name='company',
            name='type_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_organization'),
        ),
        migrations.AddField(
            model_name='company',
            name='type_regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_regime'),
        ),
    ]
