# Generated by Django 3.2.8 on 2022-05-23 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220520_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_register',
            field=models.TextField(default=datetime.date(2022, 5, 23)),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_date',
            field=models.TextField(default=datetime.date(2022, 5, 23)),
        ),
        migrations.AlterField(
            model_name='files_company',
            name='seller',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
