# Generated by Django 3.2.8 on 2022-05-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220523_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_company',
            name='seller',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
