# Generated by Django 3.2.8 on 2022-05-25 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20220524_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_register',
            field=models.TextField(default=datetime.date(2022, 5, 25)),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_date',
            field=models.TextField(default=datetime.date(2022, 5, 25)),
        ),
    ]
