# Generated by Django 3.2.13 on 2022-05-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20220531_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='from_resolution_fe',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='from_resolution_pos',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='to_resolution_fe',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='to_resolution_pos',
            field=models.TextField(default=1),
        ),
    ]
