# Generated by Django 3.2.8 on 2020-06-03 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20220602_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_register',
            field=models.TextField(default=datetime.date(2020, 6, 3)),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_date',
            field=models.TextField(default=datetime.date(2020, 6, 3)),
        ),
    ]
