# Generated by Django 3.2.8 on 2022-05-06 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleoyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentIdentification', models.TextField(unique=True)),
                ('firstname', models.TextField()),
                ('surname', models.TextField()),
                ('second_surname', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('salary', models.TextField()),
                ('user', models.TextField()),
                ('passwd', models.TextField()),
                ('block', models.BooleanField(default=False)),
                ('img', models.ImageField(default='Profile-Empleoyee/foto.jpg', upload_to='Profile-Empleoyee')),
                ('cargo', models.TextField()),
                ('hiring_date', models.TextField(default=datetime.date(2022, 5, 6))),
                ('type', models.TextField(default='Empleoyee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('payroll_type_document_identification', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='data.payroll_type_document_identification')),
                ('type_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.type_contract')),
                ('type_worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.type_worker')),
            ],
        ),
    ]
