# Generated by Django 3.2.13 on 2022-05-31 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleoyee', '0006_alter_empleoyee_hiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleoyee',
            name='hiring_date',
            field=models.TextField(default=datetime.date(2022, 5, 31)),
        ),
    ]
