# Generated by Django 3.2.13 on 2022-06-01 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleoyee', '0007_alter_empleoyee_hiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleoyee',
            name='hiring_date',
            field=models.TextField(default=datetime.date(2022, 6, 1)),
        ),
    ]
