# Generated by Django 3.2.8 on 2020-06-03 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleoyee', '0009_alter_empleoyee_hiring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleoyee',
            name='hiring_date',
            field=models.TextField(default=datetime.date(2020, 6, 3)),
        ),
    ]
